=== nemfethi/SEAAL/Nouvelle_tarification/interfaces/Facture/F3.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Document">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="LotFac">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Infos">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Lot_Type">
                                            <xs:complexType>
                                                <xs:attribute name="IdtLotTyp" type="xs:string" use="required" />
                                                <xs:attribute name="Adresse_Agence" type="xs:string" use="required" />
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="factures">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Facture">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="ID">
                                                        <xs:complexType>
                                                            <xs:attribute name="NumFct" type="xs:string" use="required" />
                                                            <xs:attribute name="DateFac" type="xs:date" use="required" />
                                                            <xs:attribute name="ClÃ©" type="xs:string" use="required" />
                                                            <xs:attribute name="Prd" type="xs:string" use="required" />
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element name="Dates">
                                                        <xs:complexType>
                                                            <xs:attribute name="Rlv" type="xs:string" use="required" />
                                                            <xs:attribute name="PrcRlv" type="xs:date" use="required" />
                                                            <xs:attribute name="Fac" type="xs:string" use="required" />
                                                            <xs:attribute name="PrcFac" type="xs:string" use="required" />
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element name="Client">
                                                        <xs:complexType>
                                                            <xs:attribute name="IdtClt" type="xs:string" use="required" />
                                                            <xs:attribute name="Nom_Prn" type="xs:string" use="required" />
                                                            <xs:attribute name="Adresse_Client" type="xs:string" use="required" />
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element name="Contrat">
                                                        <xs:complexType>
                                                            <xs:attribute name="ID" type="xs:unsignedLong" use="required" />
                                                            <xs:attribute name="Usage" type="xs:string" use="required" />
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element name="PC">
                                                        <xs:complexType>
                                                            <xs:attribute name="Adresse_PC" type="xs:string" use="required" />
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element name="Compteur">
                                                        <xs:complexType>
                                                            <xs:attribute name="NumCpr" type="xs:string" use="required" />
                                                            <xs:attribute name="Dmt" type="xs:unsignedInt" use="required" />
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element name="Info_Facture">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="Montants">
                                                                    <xs:complexType>
                                                                        <xs:attribute name="MontantHT" type="xs:float" use="required" />
                                                                        <xs:attribute name="MontantTVA" type="xs:float" use="required" />
                                                                        <xs:attribute name="MontantTTC" type="xs:float" use="required" />
                                                                        <xs:attribute name="MontantDusAnt" type="xs:float" use="required" />
                                                                        <xs:attribute name="MontantNetApayer" type="xs:float" use="required" />
                                                                        <xs:attribute name="MontantTimbre" type="xs:float" use="required" />
                                                                    </xs:complexType>
                                                                </xs:element>
                                                                <xs:element name="Lignes">
                                                                    <xs:complexType>
                                                                        <xs:sequence>
                                                                            <xs:element maxOccurs="unbounded" name="Rbq">
                                                                                <xs:complexType>
                                                                                    <xs:sequence>
                                                                                        <xs:element name="montants">
                                                                                            <xs:complexType>
                                                                                                <xs:attribute name="MntHt" type="xs:float" use="required" />
                                                                                                <xs:attribute name="MntTva" type="xs:float" use="required" />
                                                                                                <xs:attribute name="MntTtc" type="xs:float" use="required" />
                                                                                            </xs:complexType>
                                                                                        </xs:element>
                                                                                        <xs:element minOccurs="0" name="Dtls">
                                                                                            <xs:complexType>
                                                                                                <xs:sequence>
                                                                                                    <xs:element name="T1">
                                                                                                        <xs:complexType>
                                                                                                            <xs:attribute name="mnt" type="xs:float" use="required" />
                                                                                                        </xs:complexType>
                                                                                                    </xs:element>
                                                                                                    <xs:element name="T2">
                                                                                                        <xs:complexType>
                                                                                                            <xs:attribute name="mnt" type="xs:float" use="required" />
                                                                                                        </xs:complexType>
                                                                                                    </xs:element>
                                                                                                    <xs:element name="T3">
                                                                                                        <xs:complexType>
                                                                                                            <xs:attribute name="mnt" type="xs:float" use="required" />
                                                                                                        </xs:complexType>
                                                                                                    </xs:element>
                                                                                                    <xs:element name="T4">
                                                                                                        <xs:complexType>
                                                                                                            <xs:attribute name="mnt" type="xs:float" use="required" />
                                                                                                        </xs:complexType>
                                                                                                    </xs:element>
                                                                                                </xs:sequence>
                                                                                            </xs:complexType>
                                                                                        </xs:element>
                                                                                    </xs:sequence>
                                                                                    <xs:attribute name="Lbl" type="xs:string" use="required" />
                                                                                    <xs:attribute name="QtÃ©" type="xs:unsignedInt" use="optional" />
                                                                                    <xs:attribute name="PrxUnt" type="xs:float" use="optional" />
                                                                                    <xs:attribute name="TauxTva" type="xs:string" use="optional" />
                                                                                </xs:complexType>
                                                                            </xs:element>
                                                                        </xs:sequence>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="IdtLotfac" type="xs:string" use="required" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== nemfethi/SEAAL/Nouvelle_tarification/interfaces/Facture/facture.xml
<?xml version="1.1" ?>
<Document xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="F3.xsd">
    <LotFac IdtLotfac="44444">
        <Infos>
            <Lot_Type IdtLotTyp="1000" Adresse_Agence="Château d'eau Signa
                             Réghaia                
                             Alger" />
        </Infos>
        <factures>
            <Facture>
                <ID NumFct="F022320438" DateFac="2002-09-24" Clé="123454323432343234323432" Prd="3ème Trim 2020" />
                <Dates Rlv="2002-09-24" PrcRlv="2002-09-24" Fac="2002-09-24" PrcFac="2002-09-24" />
                <Client IdtClt="1200" Nom_Prn="Mohamed ben Ali" Adresse_Client="94 Cité de la GARE
            LES IRIS
            1643 REGHAIA - ALGER"></Client>
                <Contrat ID="1222234" Usage="Particulier"></Contrat>
                <PC Adresse_PC="94 Cité de la GARE
            LES IRIS
            1643 REGHAIA - ALGER" />
                <Compteur NumCpr="110PA020729" Dmt="15" />
                <Info_Facture>
                    <Montants MontantHT="1200" MontantTVA="122" MontantTTC="1333" MontantDusAnt="1222" MontantNetApayer="122" MontantTimbre="111" />
                    <Lignes>
                        <Rbq Lbl="EAU" Qté="12" PrxUnt="122" TauxTva="9%">
                            <montants MntHt="111" MntTva="111" MntTtc="111"></montants>
                            <Dtls>
                                <T1 mnt="1" />
                                <T2 mnt="1" />
                                <T3 mnt="1" />
                                <T4 mnt="1" />
                            </Dtls>
                        </Rbq>
                        <Rbq Lbl="ASS" Qté="12" PrxUnt="122" TauxTva="9%">
                            <montants MntHt="111" MntTva="111" MntTtc="111"></montants>
                            <Dtls>
                                <T1 mnt="1" />
                                <T2 mnt="1" />
                                <T3 mnt="1" />
                                <T4 mnt="1" />
                            </Dtls>
                        </Rbq>
                        <Rbq Lbl="RFETRM" Qté="12" PrxUnt="122" TauxTva="9%">
                            <montants MntHt="111" MntTva="111" MntTtc="111"></montants>
                        </Rbq>
                        <Rbq Lbl="RFATRM">
                            <montants MntHt="111" MntTva="111" MntTtc="111"></montants>
                        </Rbq>
                        <Rbq Lbl="REE">
                            <montants MntHt="111" MntTva="111" MntTtc="111"></montants>
                        </Rbq>
                        <Rbq Lbl="RQE">
                            <montants MntHt="111" MntTva="111" MntTtc="111"></montants>
                        </Rbq>
                        <Rbq Lbl="RDG">
                            <montants MntHt="111" MntTva="111" MntTtc="111"></montants>
                        </Rbq>
                    </Lignes>
                </Info_Facture>
            </Facture>
        </factures>
    </LotFac>
</Document>
